routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// auth routes - login
Auth::routes(
    [
        //disable register
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]
);

// page routes
    //home
    Route::get('/', 'ContentController@show');
    //donate
    Route::get('/geld-doneren', 'PageController@donate');
    //weergeven link
    Route::post('/link', 'DonateController@donate');
    //view danation
    Route::get('/inzage-donatie', 'PageController@viewDonation');
    //route voor unieke link
    Route::get('/inzage-donatie/{id}', 'DonateController@show');


    // admin routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.index');
        // admin contoller
        Route::resource('product', 'ProductController');
        // admin donaties
        Route::resource('donation', 'adminController');
        // admin content
        Route::resource('content', 'ContentController');
    });

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    protected $fillable = ['title','subtitle','content'];

    protected $primaryKey = 'id';
}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Content;

class ContentController extends Controller
{
    public function index(){
        $content = Content::all();
        return view('admin.content.index', compact('content'));
    }
    public function edit($id){
        $content = Content::findOrFail($id);
        return view('admin.content.edit', compact('content'));
    }
    public function update(Request $req, $id){
        $validatedData = $req->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'content' => 'required',
        ]);

        $content = Content::find($id);
        $content->title= $req->title;
        $content->subtitle= $req->subtitle;
        $content->content= $req->content;
        $content->save();

        return redirect('/content')->with('success', 'Content is geweizigd');
    }
    public function show()
    {
        // fetch all the images
        $content = Content::find(1);
        return view('pages.home', compact('content'));
    }
    public function destroy($id)
    {
        $content = Content::findOrFail($id);
        $content->delete();

        return redirect('/content')->with('success', 'Content is verwijderd');
    }
}

resources/views/admin/content/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <div class="pull-right back-btn">
        <a class="btn btn-outline-primary" href="{{ route('content.index') }}">Terug</a>
    </div>
    <form method="post" action="{{ route('content.update', $content->id) }}">
        <div class="form-group">
            @csrf
            @method('PUT')
            <label for="product_name">Kop tekst</label>
            <input type="text" class="form-control" name="title" value="{{ $content->title }}" />
        </div>
        <div class="form-group">
            <label for="product_name">Sub tekst</label>
            <input type="text" class="form-control" name="subtitle" value="{{ $content->subtitle }}" />
        </div>
        <div class="form-group">
            <label for="merk">Content</label>
            {{-- <input type="text" class="form-control" name="content" value="{{ $content->content }}"/> --}}
            <textarea style="height:50vh;" class=" form-control" name="content">
                    {{ $content->content }}
                </textarea>
        </div>
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-primary">Bewerk content</button>
    </form>
</div>
@endsection

resources/views/admin/content/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    @foreach ($content as $content)
        <form action="{{ route('content.destroy',$content->id) }}" method="POST">
            <a class="btn btn-primary" href="{{ route('content.edit',$content->id) }}">Bewerk</a>
        </form>
    @endforeach
    <hr>
    <div class="row head-text">
        <h1 class="col-12">{{ $content->title }}</h1>
        <p class="col-12">{{ $content->subtitle }}</p>
    </div>
    <div>
        {!! $content->content !!}
    </div>
</div>

@endsection