routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// auth routes - login
Auth::routes(
    [
        //disable register
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]
);

// page routes
    //home
    Route::get('/', 'ContentController@show');
    //donate
    Route::get('/geld-doneren', 'PageController@donate');
    //weergeven link
    Route::post('/link', 'DonateController@donate');
    //view danation
    Route::get('/inzage-donatie', 'PageController@viewDonation');
    //route voor unieke link
    Route::get('/inzage-donatie/{id}', 'DonateController@show');


    // admin routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.index');
        // admin contoller
        Route::resource('product', 'ProductController');
        // admin donaties
        Route::resource('donation', 'adminController');
        // admin content
        Route::resource('content', 'ContentController');
    });

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['product_name','product_price','product_price_excl_tax', 'merk','filename'];

    protected $primaryKey = 'product_id';
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        // get all products
        $product = Product::all();
        return view('admin.products.index', compact('product'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {  
        // display the create view
        return view('admin.products.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        // product validation
        $validator = Validator::make($request->all(),
            ['filename' => 'required | mimes:jpeg,png,jpg,bmp|max:1000048',
                'product_name' => 'required| max:2048',
                'product_price' => 'required',
                'product_price_excl_tax' => 'required',
                'merk' => 'required',

            ]

        );

        // if validation fails
        if ($validator->fails()) {
            return back()->withErrors($validator->errors());
        }

        // if validation product success
        if ($product = $request->file('filename')) {

            $name = time() . time() . '.' . $product->getClientOriginalExtension();

            $target_path = public_path('/productimages/');

            if ($product->move($target_path, $name)) {
                // save file name in the database
                $product = Product::create(['filename' => $name,
                    "product_name" => $request->get('product_name'),
                    "product_price" => $request->get('product_price'),
                     "merk" => $request->get('merk'),
                    "product_price_excl_tax" => $request->get('product_price_excl_tax')]);
                $product->save();
            }

        }

        return redirect('/product')->with("success", "Nieuw product toegevoegd");

    }

    /**
     *
     *
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'filename' => 'required | mimes:jpeg,png,jpg,bmp|max:1000048',
            'product_name' => 'required| max:2048',
            'product_price' => 'required| max:2048',
            'product_price_excl_tax' => 'required| max:2048',
            'merk' => 'required',
        ]);
        Product::whereId($id)->update($validatedData);

        return redirect('/product')->with('success', 'Product is geweizigd');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        return redirect('/product')->with('success', 'Product is verwijderd');
    }

}

resources/views/admin/products/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container mt-5">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                    Session::forget('success');
                @endphp
            </div>
        @endif
        <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="product_name">Product name</label>
                <input type="text" class="form-control" name="product_name" placeholder="productnaam"/>
            </div>
            <div class="form-group">
                <label for="product_price">product price :</label>
                <input type="number" step='0.01' value='0.00' placeholder='0.00' class="form-control" name="product_price"/>
            </div>
            <div class="form-group">
                <label for="merk"> merk :</label>
                <input  type="text" class="form-control" name="merk" placeholder="merk">
            </div>
         
            <div class="form-group">
                <label for="product_price_excl_tax">product price excl tax :</label>
                <input type="number" step='0.01' value='0.00' placeholder='0.00' class="form-control" name="product_price_excl_tax"/>
            </div>

            <div class="form-group">
                <div class="card ">


                    <div class="card-body">



                        <div class="form-group" {{ $errors->has('filename') ? 'has-error' : '' }}>
                            <label for="filename"></label>
                            <input type="file" name="filename" id="filename" class="form-control">
                            <span class="text-danger"> {{ $errors->first('filename') }}</span>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success btn-md"> Upload</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                Bewerk product
            </div>
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('product.update', $product->product_id) }}">
                    <div class="form-group">
                        @csrf
                        @method('PATCH')
                        <label for="product_name">Product naam:</label>
                        <input type="text" class="form-control" name="product_name" value="{{ $product->product_name }}"/>
                    </div>
                    <div class="form-group">
                        <label for="product_price">Product prijs :</label>
                        <input type="number" step='0.01' value='0.00' class="form-control" name="product_price"  value="{{ $product->product_price }}" />
                    </div>
                    <div class="form-group">
                        <label for="merk">Merk:</label>
                        <input type="text" class="form-control" name="merk" value="{{ $product->merk }}"/>
                    </div>
                    <div class="form-group">
                        <label for="product_price_excl_tax">Product prijs excl btw :</label>
                        <input type="number" step='0.01' value='0.00' class="form-control" name="product_price_excl_tax" value="{{ $product->product_price_excl_tax }}"/>
                    </div>

                    <div class="form-group" {{ $errors->has('filename') ? 'has-error' : '' }}>
                        <label for="filename"></label>
                        <input type="file" name="filename" id="filename" class="form-control">
                        <span class="text-danger"> {{ $errors->first('filename') }}</span>
                    </div>
                    <button type="submit" class="btn btn-primary">bewerk product</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">
    <div class="row create-wrap justify-content-center">
        <a href=" {{ route('product.create') }} " class="col btn btn-primary btn-sm create-button"> Add More </a>
    </div>
    <div class="row justify-content-center">
        @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
        @endif
        <div class="table-responsive custom-tbl">
            <table class="table  table-responsive">
                <thead>
                    <tr>
                        <td scope="col">ID</td>
                        <td scope="col">Productnaam</td>
                        <td scope="col">Productprijs</td>
                        <td scope="col">merk</td>
                        <td scope="col">product_price_excl_tax</td>
                        <td scope="col">Image</td>
                        <td scope="col">Actions</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($product as $product)
                    <tr>
                        <td scope="row">{{$product->id}}</td>
                        <td>{{$product->product_name}}</td>
                        <td>€{{$product->product_price}}</td>
                        <td>{{$product->merk}}</td>
                        <td>€{{$product->product_price_excl_tax}}</td>
                        <td>
                            <img src="/productimages/{{ $product->filename }} " class="img-table">
                        </td>
                        <td><a href="{{ route('product.edit', $product->product_id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <form action="{{ route('product.destroy', $product->product_id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endsection