routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// auth routes - login
Auth::routes(
    [
        //disable register
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]
);

// page routes
    //home
    Route::get('/', 'ContentController@show');
    //donate
    Route::get('/geld-doneren', 'PageController@donate');
    //weergeven link
    Route::post('/link', 'DonateController@donate');
    //view danation
    Route::get('/inzage-donatie', 'PageController@viewDonation');
    //route voor unieke link
    Route::get('/inzage-donatie/{id}', 'DonateController@show');


    // admin routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.index');
        // admin contoller
        Route::resource('product', 'ProductController');
        // admin donaties
        Route::resource('donation', 'adminController');
        // admin content
        Route::resource('content', 'ContentController');
    });

app/Donation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Donation extends Model
{
    use Sortable;
    protected $table = 'donations';

    public $primaryKey = 'id';

    public $timestamps = true;
    //toevoegen aan sortable
    public $sortable = ['donation', 'created_at'];
    //relaties
    public function email()
    {
        return $this->belongsTo('App\Email', 'id');
    }
}

resources/views/admin/donations/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Bewerk donation</h2>
            </div>
            <div class="pull-right back-btn">
                <a class="btn btn-outline-primary" href="{{ route('donation.index') }}">Terug</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('donation.update',$donation->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">

            <div class="col-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="email" name="email" value="{{ $donation->email['email'] }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Bewerk</button>
            </div>
        </div>

    </form>
</div>
    
@endsection

resources/views/admin/donations/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-sm">
    <div class="jumbotron">
        <button type="button" onclick="show()" class="btn btn-success gen-sum">Totaal bedrag</button>
        <hr>
        <h2 class="h2">Totaal donaties afgelopen 30 dagen: <span id="sum">€{{ $sum }}</span></h2>
      </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <div class="row justify-content-center">
        <div class="table-responsive custom-tbl">
            <table class="table table-dark table-responsive">
                <tr>
                    <th>Nummer</th>
                    <th>@sortablelink('donation', 'Bedrag')</th>
                    <th width="110px">Begin-datum</th>
                    <th width="110px">Eind-datum</th>
                    <th>Email</th>
                    <th>Niewsbrief</th>
                    <th width="110px">@sortablelink('created_at', 'Datum/Tijd')</th>

                    <th width="280px">Email aanpassen</th>
                </tr>
                @foreach ($donations as $donation)
                <tr>
                    <td>{{ $donation->id }}</td>
                    <td>€{{ $donation->donation }}</td>
                    <td>
                        {{ $donation->created_at->format('Y-m-d') }}
                    </td>
                    <td>
                        @if ($donation->donation_type == 'Eenmalige donatie')
                            Eenmalig
                        @else
                            @if($donation->donation_type == 'Maandelijks')
                                {{ $donation->created_at->addDays(30)->format('Y-m-d') }}  
                            @elseif($donation->donation_type == 'Elk kwartaal')
                                {{ $donation->created_at->addDays(91)->format('Y-m-d') }}  
                            @else
                                {{ $donation->created_at->addDays(365)->format('Y-m-d') }}
                            @endif
                            
                        @endif
                    </td>
                    <td>
                        {{-- get email from email table based on id --}}
                        @if ($donation->newsletter_subscription == 1 )
                            @foreach($emails->where('id', $donation->email_id) as $email)
                                {{ $email->email }}
                            @endforeach
                        @else
                            geen
                        @endif
                    </td>
                    <td>
                        @if ($donation->newsletter_subscription == 1 )
                            Ja
                        @else
                            Nee
                        @endif
                    </td>
                    <td>{{ $donation->created_at->format('Y-m-d H:i') }}</td>
                    <td>
                        <form action="{{ route('donation.destroy',$donation->id) }}" method="POST">
                            <a class="btn btn-primary" href="{{ route('donation.edit',$donation->id) }}">Bewerk</a>
                        </form>
                    </td>
                </tr>
                @endforeach
            </table>
            {!! $donations->appends(\Request::except('page'))->render() !!}
        </div>
    </div>
</div>
<script>
    //show on click
    function show() {
        var x = document.getElementById("sum");
        if (x.style.display === "none") {
        x.style.display = "inline";
        } else {
        x.style.display = "none";
        }
    }
</script>
@endsection